### PR TITLE
Merging into ClearCache branch so I know what the update is for

### PR DESCRIPTION
**Pull request by Orthrus88**

### CODE REVIEW

**Comment by Orthrus88** [comment]
Added

**Comment by Lacyway** [comment]
I like the idea of this, but instead of the ContentDialog, do you think we could use https://github.com/stayintarkov/SIT.Manager/blob/f4ab30976ee1e2f841c7fd4ba6ce0b41c6b13fee/SIT.Manager/Classes/Utils.cs#L750 instead? 

Just a suggestion, let me know what you think.

**Comment by Orthrus88** [comment]
Yeah I can update that tomorrow. Makes more sense.

**Comment by Orthrus88** [comment]
Just noticed I left Win32 in there as well. I was going to pull from the registry for the cache location. It wasn't where I thought it was so went a different route but that's left over. I'll yank that out as well.

**Comment by Orthrus88** [comment]
Updated ContentDialog to `Utils.ShowInfoBar()` and removed the 'using Microsoft.Win32;'

**Pull request merged**
