### PR TITLE
Bug Fixes, and Improvements.

### PR DESCRIPTION
**Pull request by J0nathan550**
- Fixed: Bug where user could click on the same Page as many times as he wanted. Showing off visual bug of constant transitioning
- Fixed: Window Size (removed limits), to fully maximized. What is the point of Maximized button if you cannot fully scale window on entire screen? 
- Refactored and Optimized: Connect Button. When user is trying to connect to server the entire launcher can block Main Thread, because of timeout. Added Task and handle all exceptions, now there is no Window Main Thread blocking when user accidently shutted down the Server.
- Fixed: Saving of the Last Server selected. For some reason it was cutted off?

Video of debugging: https://youtu.be/3BRr14Nsa9M?si=BXgP8z0hV-fjLECx

### CODE REVIEW

**Comment by J0nathan550** [comment]
Also, question. I saw that you didn't want to save the ServerIP to be private or what? In this pull, I save the IP again, but it's hidden nobody can see it unless you will click the box. If you need to implement 'anonymous' setting, I can do that.

**Comment by mihaicm93** [comment]
Thank you for this [J0nathan550](https://github.com/J0nathan550), I did try the PR and noticed one thing, when swaping pages and going back at the Play page, the IP is visible, would really like to have it hidden if possible, if you could do that it would be amazing

**Comment by J0nathan550** [comment]
Sure give me 20-30 minutes, I will get up.

**Comment by J0nathan550** [comment]
- Fixed weirt settings bug where if user selected one of the setting and restart launcher, it would not save the setting. At all. Even in Release this issue is exist unless you will press CheckMark on RememberMe.
- Added Setting that allows users hide their IP if they want so. Enabled by default.
Video: https://cdn.discordapp.com/attachments/947494021360656434/1211817309002534973/2024-02-27_00-19-04.mp4?ex=65ef93d0&is=65dd1ed0&hm=5ee443ba783b3d90e1fb761cccfb320748414c1b333aecb4cc944b0a9244d004&

**Pull request merged**
